version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 80:80
      - 443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod
  postgresdb:
    image: postgres:10
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: TOOLJET
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor

volumes:
  certs:
  logs:
  fallbackcerts:
